# Site settings
title: Simply Effective Solutions
copyright: 2014
copyright-text: ", inc. All rights reserved."
email: bvautier
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: ""
url: "http://orcomp.github.io/SESWebsite"
#host: localhost
include: [_colorpicker.js, _handlebars.js]

# Build settings
markdown: kramdown
permalink: pretty
