# Site settings
title: Simply Effective Solutions
copyright: 2014
copyright-text: ", inc. All rights reserved."
email: bvautier
description: "Simply Effective Solutions"
baseurl: ""
url: "http://orcomp.github.io/Web.SeSolutions"
#host: localhost
include: [_colorpicker.js, _handlebars.js]

# Build settings
markdown: kramdown
permalink: pretty
