# Site settings
title: Simply Effective Solutions
copyright: 2014 - 2015
copyright-text: ", inc. All rights reserved."
email: info@sesolutions.net.au
description: "Simply Effective Solutions"
baseurl: ""
url: "http://www.sesolutions.net.au"
#host: localhost
include: [_colorpicker.js, _handlebars.js]

# Build settings
markdown: kramdown
permalink: pretty

gems:
  - jekyll-redirect-from
  
